### PR TITLE
Add multigrid settings to flow-over-heated-plate SU2 config

### PR DESCRIPTION
**Pull request by j-signorelli**
This PR adds multigrid settings to the flow-over-heated-plate SU2 config file, speeding up runtime.

Checklist:

- [ ] I added a summary of any user-facing changes (compared to the last release) in the `changelog-entries/<PRnumber>.md`.
- [ ] I will remember to squash-and-merge, providing a useful summary of the changes of this PR.

### CODE REVIEW

**Comment by uekerman** [comment]
Could you please briefly document how much the speedup here is? Is it already significant for such a small mesh? Thanks!

**Comment by j-signorelli** [comment]
Yes of course: on my system with 3 MPI procs, without multigrid took ~444 seconds and with these multigrid settings took 168 seconds, so the speedup is 2.5-3x improvement.

**Review by MakisH — APPROVED** [review]
I have not tried to run this, but I trust that this should only improve the speed of the tutorial.

I assume you have checked that results are still the same, right?

https://precice.org/tutorials-flow-over-heated-plate.html#compare-results

**Comment by j-signorelli** [comment]
Yep! Results are indeed still the same.

**Pull request merged**
