### PR TITLE
flow-over-heated-plate: Add density and pressure to problem parameters

### PR DESCRIPTION
**Pull request by BenjaminRodenberg**
Related to #226. Currently the density is missing. This is no problem for OpenFOAM, where density defaults to 1kg/m^3 (see https://github.com/precice/tutorials/issues/226#issuecomment-888344050), but for other solvers (e.g. ELMER), where the density must be specified by the user.

# Open questions

* Do we also need density for the solid solver? Let's try to solver this in #226.

### CODE REVIEW

**Comment by DavidSCN** [comment]
I was wondering why OpenFOAM does not need the parameter and ELMER does. Before merging here, it would be interesting to see whether a coupling with ELMER using the density parameter delivers the same results as other solver combinations do.

**Comment by BenjaminRodenberg** [comment]
From my current understanding (see https://github.com/precice/tutorials/issues/226#issuecomment-892549613), I would propose to provide a density for solid and fluid. For the solid the density is technically a "don't care", but 

* this is something we can and should verify (not sure if the Elmer adapter is already far enough for this kind of verification) and
* I would still define a density (even if it is arbitrary), because this will avoid discussions in the future and make it easier for everybody who does not want to dig deep into the technical details.

For this PR this means:

* Leave it as it is
* Do some experiments with densities for more security

**Comment by DavidSCN** [comment]
> From my current understanding (see [#226 (comment)](https://github.com/precice/tutorials/issues/226#issuecomment-892549613)), I would propose to provide a density for solid and fluid. For the solid the density is technically a "don't care", but
> 

Agree

> 
> For this PR this means:
> 
>     * Leave it as it is
> 
>     * Do some experiments with densities for more security

I would vote for the second option because once we merge here nobody cares any more and we might painfully realize an issue later on.

**Comment by BenjaminRodenberg** [comment]
I just added the ambient pressure as an additional parameter. From my perspective this closes the system and allows us to derive the molar mass (if the solver requires it). See https://github.com/precice/tutorials/issues/226#issuecomment-897376368 for the derivation.

I think this PR is ready to merge. We could still perform some experiments, but since the derivation is quite simple I don't think that this is necessary anymore. @DavidSCN could you review and merge/comment?

**Review by DavidSCN — APPROVED** [review]

**Pull request merged**
