### PR TITLE
Ensure compatibility of tutorials with fenics-adapter v1.0.0

### PR DESCRIPTION
**Pull request by BenjaminRodenberg**
This PR ensures compatibility of the tutorials with v1.0.0 of the fenics-adapter (see https://github.com/precice/fenics-adapter/milestone/4).

I've collected the following relevant commits from https://github.com/precice/tutorials/tree/develop (I'll provide the commit hashes of the **original** commits below). 

We can still change the content of this PR and the list of commits below. I would like to maintain the history for this PR, if we merge it to master. I used the following strategy. If we decide that this is useful, we should document it at a proper place in the future:

1. `git checkout develop`
2. `git checkout -b fenics-adapter-v1.0.0`
3. `git rebase -i eb3283ca64932fb2d674bed1b8b677528d5c1b76`, use commits from below for rebase. (eb3283ca is the last commit that we can directly apply to `master`.)
4. `git push` to `origin/fenics-adapter-v1.0.0`
5. after merging this PR `origin/master` and `origin/fenics-adapter-v1.0.0` are even
6. `git checkout master`
7. `git pull`
8. `git checkout develop`
9. `git merge master` (might be a better idea to `rebase` here to avoid duplicates)
10. `git push` to `origin/develop` (then we will have to `git push --force` to `develop`)

### Required commits:

```
# pick 0382555 Update case according to https://github.com/precice/fenics-adapter/pull/81
# pick c764405 Update get_point_sources
# pick a178d1c Update get_point_sources
# pick 7d4eb3c Revert "Update get_point_sources"
# pick 407a235 Uses new SegregatedRBFInterpolationExpression from https://github.com/precice/fenics-adapter/pull/83
pick 88d2db5 Add valid interpolation strategy.
pick 475e406 Use rbf_segregated
pick c9d7408 Removes interpolation_type from all fenics adapter config files.
pick 7b74954 Fix output frequency of Solid
pick 8a51b25 Make output routine with dt_out more robust
pick ece21a0 Use same method for flux computation like in HT example. (#114)
pick f33edb6 Rename fenicsadapter to fenicsprecice (#113)
pick c20e1c3 Convert dt to float (#115)
pick 41b1a46 Initial change to FEniCS-Adapter initialization
pick ca1b1dd Merging write_function_space and write_function into write_object
pick 42bd9c5 Explicitly mentioning optional parameter names in adapter initialization
pick 860642a Adding comment to explain why a function space is passed twice to initialization
pick fdbee1b Initialize with V_g.sub(1) as write_object (#127)
pick bb5d51b Add SU2-FEniCS Perpendicular Flap FSI Tutorial (#91)
pick 1c891a7 Modify FEniCS tutorials to enable parallel runs (#120)
pick 107c076 Move */OpenFOAM-FEniCS to *_2D/OpenFOAM-FEniCS. (#141)
pick 595409d Ensuring consistency in FEniCS scripts for FSI tutorial cases  (#142)
pick ae77ae5 Fix ill-posed problem by providing additional data. (#144)
```

## Shortcomings

If there is a better strategy, feedback would be very welcome. A big downside of the current strategy is that for each commit a new hash is generated. This means that as soon as we merge `develop` into master (i.e. next regular release), we will duplicate all commits from this PR. We can already see this in the `log` of `develop` after the last step described above:

```
commit f9c16f74955657593c2c8917e9e30e83c4919596 (HEAD -> develop)
Merge: 1c891a7 a1ca149
Author: BenjaminRueth <benjamin.rueth@tum.de>
Date:   Sun Dec 20 15:47:01 2020 +0100

    Merge branch 'master' into develop

commit a1ca14935f39fc22ffe33ed0dc877fd9422a713c (origin/fenics-adapter-v1.0.0, master, fenics-adapter-v1.0.0)
Author: Ishaan Desai <44898158+IshaanDesai@users.noreply.github.com>
Date:   Sat Dec 19 18:15:54 2020 +0100

    Modify FEniCS tutorials to enable parallel runs (#120)
    
    * Modifying all FEniCS based tutorials to be compatible with parallel design of FEniCS-Adapter
    Co-authored-by: BenjaminRueth <benjamin.rueth@tum.de>

commit 55232e384bd8dc5c48dc68834dc03b0d3527f7af
Author: Ishaan Desai <44898158+IshaanDesai@users.noreply.github.com>
Date:   Sat Dec 19 17:47:24 2020 +0100

    Add SU2-FEniCS Perpendicular Flap FSI Tutorial (#91)
    
    * Adding 2D perpendicular flap FSI tutorial with SU2-FEniCS
    Co-authored-by: Benjamin Rüth <benjamin.rueth@tum.de>

commit c410372a24f7c2316b533fb90392ee66426c34ae
Author: Benjamin Rüth <benjamin.rueth@tum.de>
Date:   Thu Dec 10 17:19:03 2020 +0100

    Initialize with V_g.sub(1) as write_object (#127)

commit 1c891a7882ddf3a2abdfa50ecafb941f1395eebb (origin/develop)
Author: Ishaan Desai <44898158+IshaanDesai@users.noreply.github.com>
Date:   Sat Dec 19 18:15:54 2020 +0100

    Modify FEniCS tutorials to enable parallel runs (#120)
    
    * Modifying all FEniCS based tutorials to be compatible with parallel design of FEniCS-Adapter
    Co-authored-by: BenjaminRueth <benjamin.rueth@tum.de>

commit bb5d51b27be037f8a7e579a43ba878b7ece25bf6
Author: Ishaan Desai <44898158+IshaanDesai@users.noreply.github.com>
Date:   Sat Dec 19 17:47:24 2020 +0100

    Add SU2-FEniCS Perpendicular Flap FSI Tutorial (#91)
    
    * Adding 2D perpendicular flap FSI tutorial with SU2-FEniCS
    Co-authored-by: Benjamin Rüth <benjamin.rueth@tum.de>

...

commit 8cf97fda8a4a4d3c551fd4a970e3f939c7be6167
Author: Benjamin Rüth <benjamin.rueth@tum.de>
Date:   Sun Nov 8 16:06:49 2020 +0100

    Convert dt to float (#115)

...

commit c20e1c396c402b9ad5b7c6b581ffb45ef26a91e1
Author: Benjamin Rüth <benjamin.rueth@tum.de>
Date:   Sun Nov 8 16:06:49 2020 +0100

    Convert dt to float (#115)

```

### CODE REVIEW

**Comment by BenjaminRueth** [comment]
I now decided to use `git rebase -i` instead of `git cherry-pick`. I removed all the commits that we do not need in this interactive session (see above). This keeps the original hashes of 03825552c4db145413c697868d3cc80a4886264a and c764405e3b671a1e37fb1910a21fa5e49b01b1ec. However, later commits will still get a new hash.

**Comment by BenjaminRueth** [comment]
What will happen with this PR in the future? We will first merge `fenics-adapter-v1.0.0@3d87fe8` into `master@95cc1ed`. Then `master@3d87fe8` into `develop@0252594` to synchronize both branches. At some point in time in the future (regular release) we will merge `develop@xxxxxxx` (in example below this is the merge commit `9c13a46`) into `master@3d87fe8`. I already followed this strategy locally and got the following output for the merge of `develop` into `master`:
```
benjamin@benjamin-ThinkPad-X1-Yoga-2nd:~/tutorials$ git merge develop 
Updating 3d87fe8..9c13a46
Fast-forward
 CHT/flow-over-plate/buoyantPimpleFoam-nutils/Nutils/cht.py                     |   2 +-
 FSI/cylinderFlap_2D/OpenFOAM-deal.II/Fluid/0.orig/U                            |  13 ++--
 FSI/cylinderFlap_2D/OpenFOAM-deal.II/Fluid/constant/dynamicMeshDict            |   0
 FSI/cylinderFlap_2D/OpenFOAM-deal.II/Fluid/system/blockMeshDict                |  34 +++++-----
 FSI/cylinderFlap_2D/OpenFOAM-deal.II/Fluid/system/blockMeshDict_double_refined | 346 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 FSI/cylinderFlap_2D/OpenFOAM-deal.II/Fluid/system/blockMeshDict_refined        | 346 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 FSI/cylinderFlap_2D/OpenFOAM-deal.II/Fluid/system/controlDict                  |  19 +++++-
 FSI/cylinderFlap_2D/OpenFOAM-deal.II/Fluid/system/decomposeParDict             |   4 +-
 FSI/cylinderFlap_2D/OpenFOAM-deal.II/Fluid/system/fvSchemes                    |  16 +----
 FSI/cylinderFlap_2D/OpenFOAM-deal.II/Fluid/system/fvSolution                   |  65 +++++++++++-------
 FSI/cylinderFlap_2D/OpenFOAM-deal.II/README.md                                 |   2 +-
 FSI/cylinderFlap_2D/OpenFOAM-deal.II/Solid/linear_elasticity.prm               |   4 +-
 FSI/cylinderFlap_2D/OpenFOAM-deal.II/Solid/nonlinear_elasticity.prm            |   2 +-
 FSI/cylinderFlap_2D/OpenFOAM-deal.II/plotDisplacement.sh                       |   9 +++
 FSI/cylinderFlap_2D/OpenFOAM-deal.II/precice-config.xml                        | 117 +++++++++++++++-----------------
 FSI/flap_perp/OpenFOAM-CalculiX/README.md                                      |   2 +-
 FSI/flap_perp/SU2-CalculiX/Allclean                                            |  54 +++++++++++++++
 FSI/flap_perp/SU2-CalculiX/Allrun                                              |  77 +++++++++++++++++++++
 FSI/flap_perp/SU2-CalculiX/Fluid/euler_config_coupled.cfg                      |  13 +++-
 FSI/flap_perp/SU2-CalculiX/Fluid/euler_config_coupled_mergeSolution.cfg        | 267 -----------------------------------------------------------------------
 FSI/flap_perp/SU2-CalculiX/README.md                                           |   8 ++-
 FSI/flap_perp/SU2-CalculiX/plotDisplacement.sh                                 |   2 +-
 FSI/flap_perp/SU2-CalculiX/precice-config.xml                                  |   2 +-
 FSI/flap_perp/SU2-CalculiX/runFluid                                            |  25 +++++++
 FSI/flap_perp/SU2-CalculiX/runSolid                                            |  14 ++++
 FSI/flap_perp/SU2-CalculiX/runTutorial_parallel.sh                             |  48 -------------
 FSI/flap_perp/SU2-CalculiX/runTutorial_serial.sh                               |  46 -------------
 27 files changed, 1033 insertions(+), 504 deletions(-)
 mode change 100755 => 100644 FSI/cylinderFlap_2D/OpenFOAM-deal.II/Fluid/constant/dynamicMeshDict
 create mode 100644 FSI/cylinderFlap_2D/OpenFOAM-deal.II/Fluid/system/blockMeshDict_double_refined
 create mode 100644 FSI/cylinderFlap_2D/OpenFOAM-deal.II/Fluid/system/blockMeshDict_refined
 create mode 100755 FSI/cylinderFlap_2D/OpenFOAM-deal.II/plotDisplacement.sh
 create mode 100755 FSI/flap_perp/SU2-CalculiX/Allclean
 create mode 100755 FSI/flap_perp/SU2-CalculiX/Allrun
 delete mode 100644 FSI/flap_perp/SU2-CalculiX/Fluid/euler_config_coupled_mergeSolution.cfg
 create mode 100755 FSI/flap_perp/SU2-CalculiX/runFluid
 create mode 100755 FSI/flap_perp/SU2-CalculiX/runSolid
 delete mode 100755 FSI/flap_perp/SU2-CalculiX/runTutorial_parallel.sh
 delete mode 100755 FSI/flap_perp/SU2-CalculiX/runTutorial_serial.sh
```
This looks good to me. Obviously all changes that affect FEniCS-bases tutorials have already been merged into master via #124. The only changes that are remaining are the ones not connected to FEniCS.

**Review by IshaanDesai — APPROVED** [review]
Manual check of all tutorials is done. All good :+1:

**Comment by BenjaminRueth** [comment]
@MakisH , @fsimonis: Can you comment on this PR? Not really on the content, but more on the general git merging strategy? Please speak up, if you think everything is a horrible idea. I think we will have to be careful with the merge `master -> develop` technically we cannot do anything wrong with merging this PR (yet).

**Review by MakisH — COMMENTED** [review]
I am not sure I follow everything, but I understand that you did several changes in your branch, and now you want to merge to master. For some reason I don't fully understand, we will get some duplicate (empty) commits when we merge from develop to master in the next release.

Here are a few thoughts:
- All the changes here are related to FEniCS (good).
- The history of the tutorials is already quite dirty. I would not worry too much, you already seem to have thought well of every step.
- Since you are afraid that something go wrong when we merge develop to master, you can have the honor to do it yourself when it's time to release. :wink: I am optimistic that things will not go so bad. Worst case, we have to resolve some merge conflicts.
- The most important aspect I see is to merge these changes soon and to then synchronize the restructuring branch soon afterwards.
- Finally, I don't like the idea of directly merging to master right now. Do you have a good reason for this? Why skip develop? Why not merge to develop and then merge develop to master soon after? We don't need to wait for the next preCICE release to update the tutorials, develop still works perfectly fine with preCICE v2.1.1.

**Comment by BenjaminRueth** [comment]
Thanks for the comment!

> I am not sure I follow everything, but I understand that you did several changes in your branch, and now you want to merge to master. For some reason I don't fully understand, we will get some duplicate (empty) commits when we merge from develop to master in the next release.

Important information that is missing: This is not a feature branch, but one where I collected all the FEniCS-related changes from develop.

> Here are a few thoughts:
> 
> * All the changes here are related to FEniCS (good).
> 
> * The history of the tutorials is already quite dirty. I would not worry too much, you already seem to have thought well of every step.
> 
> * Since you are afraid that something go wrong when we merge develop to master, you can have the honor to do it yourself when it's time to release. wink I am optimistic that things will not go so bad. Worst case, we have to resolve some merge conflicts.

Sounds at least, like I did not commit any major git sins ;)

> * The most important aspect I see is to merge these changes soon and to then synchronize the restructuring branch soon afterwards.

Fully agree: I really would like to do a release before #125.

> * Finally, I don't like the idea of directly merging to master right now. Do you have a good reason for this? 

Main reason: We want to release the fenics-adapter soon and therefore also have a corresponding release of the tutorials.

> Why skip develop? 

The changes from this branch are already part of develop.

> Why not merge to develop and then merge develop to master soon after? 

The main reason I'm not directly merging develop into master is since I don't want to risk breaking the other tutorials that are not related to FEniCS (i.e. Deal.II).

> We don't need to wait for the next preCICE release to update the tutorials, develop still works perfectly fine with preCICE v2.1.1.

If the current state of develop is ready for releasing, we can also just do a "normal" release and close this PR. But then we will not have the "nice" FEniCS-only release ("All the changes here are related to FEniCS (good).")

**Comment by MakisH** [comment]
> > Why not merge to develop and then merge develop to master soon after?
> 
> The main reason I'm not directly merging develop into master is since I don't want to risk breaking the other tutorials that are not related to FEniCS (i.e. Deal.II).

I don't see any such issue at the moment. I see more problematic bypassing our branching model (as you already pointed out that it may need some ninja tricks to not end up with spaghetti bolognese).

> > We don't need to wait for the next preCICE release to update the tutorials, develop still works perfectly fine with preCICE v2.1.1.
> 
> If the current state of develop is ready for releasing, we can also just do a "normal" release and close this PR. But then we will not have the "nice" FEniCS-only release ("All the changes here are related to FEniCS (good).")

You could do a similar thing targetting the develop branch next time (since now everything is already in develop). If you need it for future reference, you can always close this and the diff will remain (at least if the branch remains).

Other than being able to easily check what we needed to change, I don't see a reason to make it a "FEniCS-only release". The develop should always be releasable (more on this in the context of our versioning strategy).

**Comment by BenjaminRueth** [comment]
> > > Why not merge to develop and then merge develop to master soon after?
> > 
> > 
> > The main reason I'm not directly merging develop into master is since I don't want to risk breaking the other tutorials that are not related to FEniCS (i.e. Deal.II).
> 
> I don't see any such issue at the moment. I see more problematic bypassing our branching model (as you already pointed out that it may need some ninja tricks to not end up with spaghetti bolognese).
> 
> > > We don't need to wait for the next preCICE release to update the tutorials, develop still works perfectly fine with preCICE v2.1.1.
> > 
> > 
> > If the current state of develop is ready for releasing, we can also just do a "normal" release and close this PR. But then we will not have the "nice" FEniCS-only release ("All the changes here are related to FEniCS (good).")
> 
> You could do a similar thing targetting the develop branch next time (since now everything is already in develop). If you need it for future reference, you can always close this and the diff will remain (at least if the branch remains).
> 
> Other than being able to easily check what we needed to change, I don't see a reason to make it a "FEniCS-only release". The develop should always be releasable (more on this in the context of our versioning strategy).

Ok. Then I will close this PR and open a "real" release PR from develop to master. This avoids spaghetti bolognese and ninja tricks ;) If nobody stops me: As soon as the systemtests are good.

**Comment by uekerman** [comment]
> Other than being able to easily check what we needed to change, I don't see a reason to make it a "FEniCS-only release". The develop should always be releasable (more on this in the context of our versioning strategy).

But then we need to release everything else now as well? (all adapters) That's sth we wanted to avoid with the new release strategy, right? It needs to be possible to only release the FEniCS adapter.

**Comment by MakisH** [comment]
Well... we have not yet fixed how we want to do things (we should).

What we have discussed already is a versioning scheme and when to release what. We concluded that the tutorials can be released whenever needed, not only with preCICE releases. But we did not discuss if & how we want to release specific changes.

The main issue we addressed is what to do with breaking changes / which branches to test together. The if and how we want to release specific tutorials is a bit unclear to me at the moment. Our current strategy is still "feature --> develop --> master".

**Comment by BenjaminRueth** [comment]
> > Other than being able to easily check what we needed to change, I don't see a reason to make it a "FEniCS-only release". The develop should always be releasable (more on this in the context of our versioning strategy).
> 
> But then we need to release everything else now as well? (all adapters) That's sth we wanted to avoid with the new release strategy, right? It needs to be possible to only release the FEniCS adapter.

I think this is the main thing we have to decide now: git ninja spaghetti merge, but only FEniCS (#124) or simple, but everything (#132). I understand from https://github.com/precice/tutorials/pull/124#issuecomment-748846354 that releasing everything is no problem, since there are not breaking changes besides FEniCS. This is nothing that we can expect generally, but this time we might be able to get away with the simple approach (#132).

**Comment by MakisH** [comment]
I just see as "let's still use the usual old model we had until now, as the new one is not yet defined & ready".

**Comment by BenjaminRueth** [comment]
Like mentioned in https://github.com/precice/tutorials/pull/124#issuecomment-748980624, we want to test the release strategy "only release FEniCS stuff" with this PR. Reopening this PR and closed #132.

@MakisH, @uekerman, @fsimonis please approve, if you are fine with me merging this PR into `master`. 

As soon as this PR is merged, I will cleanup develop (might require some force pushing). See steps 9. and 10. in https://github.com/precice/tutorials/pull/124#issue-533724717.

**Comment by uekerman** [comment]
Why do we need the force push? A simple merge should be enough?

**Review by MakisH — APPROVED** [review]
My only concern is that at the end `master` does not go ahead of `develop`. But since these changes are already in `develop`, go ahead and merge. Everything should be fine and if not, we will fix it. :smile:

**Comment by IshaanDesai** [comment]
It is worth to note that merging this PR sends the following failing tutorials to `master`:
* `FSI/cylinderFlap/OpenFOAM-FEniCS`: https://github.com/precice/tutorials/issues/140
* `FSI/flap_perp/OpenFOAM-FEniCS`: https://github.com/precice/tutorials/issues/131

These failures occurred when the handling of the 2D-3D data mapping was shifted from the FEniCS side to the OpenFOAM side. In a way these failures can be seen as *not relevant* from the `fenics-adapter-v1.0.0` perspective. But they are worth noting and need fixing in the end.

**Comment by MakisH** [comment]
>  In a way these failures can be seen as _not relevant_ from the `fenics-adapter-v1.0.0` perspective.

Well... this is a release of the tutorials, not only of the FEniCS adapter, so the new cases should work (before they get into develop). Are these cases new or have they been working before? Does the current state work (with the "old" FEniCS adapter)?

**Comment by IshaanDesai** [comment]
> Well... this is a release of the tutorials, not only of the FEniCS adapter, so the new cases should work (before they get into develop). 

Yes, I agree. These tutorials need to be fixed.

> Are these cases new or have they been working before? Does the current state work (with the "old" FEniCS adapter)?

The tests are not new, they existed before the re-design of the FEniCS-Adapter. The main difference was that previously in the `precice-config` it was `<solver-interface dimensions="3">` but now it is `<solver-interface dimensions="2">`. This transfers the 2D-3D data conversion to the OpenFOAM side. Apart from removal of the 2D-3D mechanism there are no algorithmic changes to the way the coupled problem is solved on the FEniCS side. The FEniCS-Adapter is now *purely 2D*.

**Review by MakisH — CHANGES_REQUESTED** [review]
It was not clear to me before that the OpenFOAM-FEniCS cases are now using a 2D solver interface. They should be moved into the `*_2D` case directories for now.

@IshaanDesai also pointed out that the cases OpenFOAM-FEniCS currently don't work, so let's have another look at it first.

Note that in the tutorials restructuring we plan to remove all the `cylinder-flap` cases, apart from the (now validated) Turek&Hron FSI3 case. So, we could just remove this case already. We should only focus on the perpendicular flap (solid participant), used with the exact same fluid configuration,

**Comment by BenjaminRueth** [comment]
> Why do we need the force push? A simple merge should be enough?

I can describe how the merge looks like locally. I hope that this makes the workflow more clear (also to myself):

## No need for `git push force`

### 1) Current state of master

```
$ git checkout master
$ git log
commit 95cc1ed1294c9c9e5af4d6bcc6393be4cd8dcb53 (HEAD -> master, origin/master, origin/HEAD)
Merge: 43de322 0babb87
Author: David Schneider <dav.schneider@tum.de>
Date:   Wed Jul 29 10:48:31 2020 +0200

    Merge pull request #98 from precice/dii_readme
    
    Add missing deal.II README files

...
```

### 2) Do the merge #124 into `master`
```
$ git merge fenics-adapter-v1.0.0
Updating 95cc1ed..a1ca149
Fast-forward
...
$ git log
commit a1ca14935f39fc22ffe33ed0dc877fd9422a713c (HEAD -> master, origin/fenics-adapter-v1.0.0, fenics-adapter-v1.0.0)
Author: Ishaan Desai <44898158+IshaanDesai@users.noreply.github.com>
Date:   Sat Dec 19 18:15:54 2020 +0100

    Modify FEniCS tutorials to enable parallel runs (#120)
    
    * Modifying all FEniCS based tutorials to be compatible with parallel design of FEniCS-Adapter
    Co-authored-by: BenjaminRueth <benjamin.rueth@tum.de>

commit 55232e384bd8dc5c48dc68834dc03b0d3527f7af
Author: Ishaan Desai <44898158+IshaanDesai@users.noreply.github.com>
Date:   Sat Dec 19 17:47:24 2020 +0100

    Add SU2-FEniCS Perpendicular Flap FSI Tutorial (#91)
    
    * Adding 2D perpendicular flap FSI tutorial with SU2-FEniCS
    Co-authored-by: Benjamin Rüth <benjamin.rueth@tum.de>
...
commit 03825552c4db145413c697868d3cc80a4886264a
Author: BenjaminRueth <benjamin.rueth@tum.de>
Date:   Tue Aug 11 09:47:46 2020 +0200

    Update case according to https://github.com/precice/fenics-adapter/pull/81

commit 95cc1ed1294c9c9e5af4d6bcc6393be4cd8dcb53 (origin/master, origin/HEAD, fenics-adapter-v1.0.0-merge)
Merge: 43de322 0babb87
Author: David Schneider <dav.schneider@tum.de>
Date:   Wed Jul 29 10:48:31 2020 +0200

    Merge pull request #98 from precice/dii_readme
    
    Add missing deal.II README files
```
### 3) Synchronize `master` and `develop` via `git merge master`
```
$ git checkout develop
$ git merge master
$ git log
commit 4ee6c5b0dcf5d392ac02850dbc672999759e63b5 (HEAD -> develop)
Merge: 1c891a7 a1ca149
Author: BenjaminRueth <benjamin.rueth@tum.de>
Date:   Mon Dec 21 22:13:21 2020 +0100

    Merge branch 'master' into develop

commit a1ca14935f39fc22ffe33ed0dc877fd9422a713c (origin/fenics-adapter-v1.0.0, master, fenics-adapter-v1.0.0)
Author: Ishaan Desai <44898158+IshaanDesai@users.noreply.github.com>
Date:   Sat Dec 19 18:15:54 2020 +0100

    Modify FEniCS tutorials to enable parallel runs (#120)
    
    * Modifying all FEniCS based tutorials to be compatible with parallel design of FEniCS-Adapter
    Co-authored-by: BenjaminRueth <benjamin.rueth@tum.de>

...

commit 1c891a7882ddf3a2abdfa50ecafb941f1395eebb (origin/release_for_fenics-adapter-v1.0.0, origin/dev
elop, release_for_fenics-adapter-v1.0.0)
Author: Ishaan Desai <44898158+IshaanDesai@users.noreply.github.com>
Date:   Sat Dec 19 18:15:54 2020 +0100

    Modify FEniCS tutorials to enable parallel runs (#120)
    
    * Modifying all FEniCS based tutorials to be compatible with parallel design of FEniCS-Adapter
    Co-authored-by: BenjaminRueth <benjamin.rueth@tum.de>

...
```
Here a1ca14935f39fc22ffe33ed0dc877fd9422a713c is the commit originating from this PR, while 1c891a7882ddf3a2abdfa50ecafb941f1395eebb is the original commit from develop. These kind of duplicates show up very often.

## Requires `git push force`

First two steps are the same.

### 3) Synchronize `master` and `develop` via `git ???`

*will add this soon*

**Comment by BenjaminRueth** [comment]
If anybody has comments on why `push --force` to develop is a bad idea, feel free to comment. I think it might backfire to some degree, when we want to merge feature branches (that already exist today) into develop (after `push --force`). However: I do not see another solution and the trade-off is:

Developers having nightmares and fighting with git vs. having duplicates in history on master. The first is short-term pain while the second is something that might backfire in the future and we cannot fix it anymore.

**Comment by BenjaminRueth** [comment]
> It was not clear to me before that the OpenFOAM-FEniCS cases are now using a 2D solver interface. They should be moved into the `*_2D` case directories for now.

This is something that has to be changed directly on `develop`. As soon as these changes are on `develop` I can merge them into this release PR.

**Comment by BenjaminRodenberg** [comment]
@IshaanDesai can you check again? I removed your previously pushed commit, since this a release branch. But actually something was wrong with my previous `rebase`. So good that you detected the error.

**Review by IshaanDesai — APPROVED** [review]
Applying changes from: https://github.com/precice/tutorials/pull/142 will finalize the compatibility of tutorials with fenics-adapter v1.0.1

**Comment by BenjaminRodenberg** [comment]
Just had a short concluding discussion with @IshaanDesai and @uekerman on this:

* No `push --force` to `develop` :exclamation: Doing a `push --force` would allow us to keep `master` tidy (also in the future), but drive everybody using `develop` crazy, because commits on `develop` would be overwritten.
* Do a `merge` of `master` into `develop` after the release. There should not be any merge conflicts, if everything is done correctly here. This will duplicate commits that were introduced in this PR via `cherry-pick`. However, this is the preferable way to mess up our history :smirk: 

I will take care of the last few necessary synchronizations of this PR to `develop` and then merge into master as soon as https://github.com/precice/fenics-adapter/pull/114 (`v1.0.1`) is released, if nobody protests.

**Pull request merged**
