### PR TITLE
flow-over-heated-plate: Remove unnecessary parameter

### PR DESCRIPTION
**Pull request by BenjaminRodenberg**
See https://github.com/precice/tutorials/issues/226#issuecomment-896933844: From my current perspective, we do not need `nMoles`.

### CODE REVIEW

**Comment by BenjaminRodenberg** [comment]
I also removed `nMoles` in the cases `flow-over-heated-plate-steady-state` and `flow-over-heated-plate-nearest-projection`, but did not check any results.

**Comment by MakisH** [comment]
Have you also tried this with different OpenFOAM versions? I can imagine that this was there for technical reasons, even if not used. But most probably this originates from the very first prototypes, which were probably also based on something else (as is common in OpenFOAM).

**Comment by BenjaminRodenberg** [comment]
> Have you also tried this with different OpenFOAM versions?

Of course, not :smirk:

**Comment by uekerman** [comment]
@BenjaminRodenberg Don't forget the changelog entry.

**Review by MakisH — APPROVED** [review]
Indeed. From the [OpenFOAM 8 docs](https://cfd.direct/openfoam/user-guide/v8-thermophysical/):

> nMoles: number of moles of component. This entry is only used for combustion modelling based on regress variable with a homogeneous mixture of reactants; otherwise it is set to 1.

**Review by MakisH — APPROVED** [review]
This looks correct. From the OpenFOAM.org user guide:

> nMoles: number of moles of component. This entry is only used for combustion modelling based on regress variable with a homogeneous mixture of reactants; otherwise it is set to 1.

**Pull request merged**
