### PR TITLE
Use beta consistent with literature

### PR DESCRIPTION
**Pull request by BenjaminRodenberg**
Closes https://github.com/precice/precice/commit/b8ba60bf8b6034d676aeec9e73bb366bebcfe848

Comments for the review: Am I missing some tutorial?

### CODE REVIEW

**Review by IshaanDesai — APPROVED** [review]
I think you have got all the cases.

**Review by davidscn — COMMENTED** [review]
Hm, the proposed changes here contradict what we do in the OpenFOAM adapter paper. There, we use 1.3 and even refer to the tutorials

> We select α = 3 and β = 1.3, as used in the preCICE tutorials with other solvers

We selected these parameters due to their value in the tutorial. @MakisH opinions?

**Comment by MakisH** [comment]
I remember discussing this a while ago. I think it was wrong, but kept it to stick with the tutorials.

In the OpenFOAM-preCICE paper, we refer to a specific version of the tutorials, so I think we should not be restricted by that. Consistency is more important.

**Comment by BenjaminRodenberg** [comment]
Ok. So approved? @MakisH @davidscn

**Review by MakisH — APPROVED** [review]

**Pull request merged**
