### PR TITLE
Rename fenicsadapter to fenicsprecice

### PR DESCRIPTION
**Pull request by BenjaminRueth**
Ensures compatibility with changes introduced in https://github.com/precice/fenics-adapter/commit/fef80b749b5e40f42c3d3b30c18d0dfe9a2d1ea2

### CODE REVIEW

**Comment by BenjaminRueth** [comment]
@IshaanDesai I hope that I'm not missing something. Can you double-check?

**Review by MakisH — CHANGES_REQUESTED** [review]
Attention: please change the target branch to `develop` first.

**Comment by BenjaminRueth** [comment]
> Attention: please change the target branch to `develop` first.

Done. Thanks for the hint!

**Review by MakisH — APPROVED** [review]
With a quick look, it looks ok. Target branch ok, the code you changed should not cause any effects in other parts.

**Pull request merged**
