### PR TITLE
Remove 'not yet ported warning'

### PR DESCRIPTION
**Pull request by DavidSCN**
to be merged at the very end when we merge #160. The website introduction site needs to be adjusted as well.

### CODE REVIEW

**Comment by uekerman** [comment]
> The website introduction site needs to be adjusted as well.

Should we do this here?

**Comment by DavidSCN** [comment]
We can't, the site is located here https://github.com/precice/precice.github.io/blob/master/pages/tutorials/tutorials.md

**Comment by MakisH** [comment]
We need to first merge develop and apply the same change for partitioned-pipe and anything else that we may have added since.

**Comment by DavidSCN** [comment]
Done. The `elastic-tube-1d` has still this warning, but there is no valuable README/tutorial at all.

**Pull request merged**
