### PR TITLE
Release for fenics adapter v1.0.0

### PR DESCRIPTION
**Pull request by BenjaminRueth**
This is now a "real" release originating from the discussion in #124.

This release is published to provide a version of the tutorials that is compatible with the [upcoming v1.0.0 release of the fenics-adapter](https://github.com/precice/fenics-adapter/releases/tag/untagged-a0d39f3fcf28a8d12ae1).

I will add a tag `fenics-adapter-v1.0.0` as soon as this PR is merged. Similar to [here](https://github.com/precice/tutorials/releases/tag/precice-v1.6).

### CODE REVIEW

**Review by MakisH — CHANGES_REQUESTED** [review]
This still merges directly from a specific branch to master. What we want is to merge develop to master.

**Comment by BenjaminRueth** [comment]
> This still merges directly from a specific branch to master. What we want is to merge develop to master.

So no release branch? Also ok.

**Comment by MakisH** [comment]
> > This still merges directly from a specific branch to master. What we want is to merge develop to master.
> 
> So no release branch? Also ok.

Ah, it was not clear to me that this is a release branch that has everything already on develop (we have not yet standardized this). Then this is fine, I will have a look later today.

**Review by IshaanDesai — APPROVED** [review]
The following two tutorials produce errors on the OpenFOAM side:
* `FSI/cylinderFlap/OpenFOAM-FEniCS`
* `FSI/flap_perp/OpenFOAM-FEniCS`

Rest everything works, confirmed by manual checks :+1:

**Comment by BenjaminRueth** [comment]
Closing this one in favor of #124. We actually want to give the approach in #124 a chance in order to find out whether it is possible to release only a part of the tutorials without driving everybody crazy. This PR (#132) is git-wise much more simple than #124, but does not meet the requirement "only release FEniCS stuff".

**Pull request closed without merging**
