### PR TITLE
elastic-tube-1d: Remove unnecessary read statement

### LINKED ISSUE #231: elastic-tube-1d: Unnecessary readBlockScalarData
The following `readBlockScalarData` statements looks wrong and is inconsistent with the python version of the 1d tube:

https://github.com/precice/tutorials/blob/6d90ae3eb179113beb400e472c8832e29a48db9b/elastic-tube-1d/fluid-cpp/src/FluidSolver.cpp#L104-L106

Compared to the original code (see https://github.com/precice/elastictube1d/blob/master/fluid-cpp/FluidSolver.cpp) this statement has been added. Is there a specific reason?

I did some experiments related to this change and will document them here, since this might be helpful for https://github.com/precice/precice/pull/1036:

| commit | comment | `fluid-cpp` + `solid-cpp` remove statement above (fa75a39) | `fluid-cpp` + `solid-cpp` keep statement above (46ce8abee8dea365005da40f6e016a12f4bd97fd) | `fluid-python` + `solid-python` (46ce8abee8dea365005da40f6e016a12f4bd97fd) |
|----------------------------------------------------------------------------------------------------------------------|---|---|---|---|
https://github.com/precice/precice/commit/3ff0899092862ad6f081df033ca9b51d0041befa | pre https://github.com/precice/precice/pull/1004| :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark:  |
https://github.com/precice/precice/commit/54707b3902af7d79b28ac276f304c31c6fcf5433 |  current state https://github.com/precice/precice/pull/1036 | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
https://github.com/precice/precice/commit/40eca9dea4802f8dc59426eeefc39d95269042a4 |  current state `precice:develop` | :x: | :x:  | :x: |
https://github.com/precice/precice/commit/c9c90b23abbe0ec9380266d68c51c75374ab6a81 | merge `precice:develop` into https://github.com/precice/precice/pull/1036 | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark:  |

:heavy_check_mark: -> elastic-tube-1d works as expected
:x: -> elastic-tube-1d breaks as described in https://github.com/precice/precice/issues/1032

### PR DESCRIPTION
**Pull request by BenjaminRodenberg**
Closes #231

### CODE REVIEW

**Comment by MakisH** [comment]
Could you please rename the PR to clearly refer to elastic-tube-1d and to what it is changing? It would be easier to parse the PR list in the future.

**Comment by MakisH** [comment]
Rebasing on develop should fix the failing "Check links" workflow.

**Comment by BenjaminRodenberg** [comment]
This PR implements the following approach from https://github.com/precice/tutorials/issues/231#issuecomment-889806830:

```
initialize
read
while(ongoing){
  solve
  write
  advance
  read
}
```

**Comment by uekerman** [comment]
Don't forget the changelog entry

**Review by MakisH — APPROVED** [review]

**Pull request merged**
