### PR TITLE
Throw error in fenics and nutils run scripts if no argument was provided 

### PR DESCRIPTION
**Pull request by DavidSCN**
Nothing happens if no argument was provided, which is a bit unfortunate for people like me who are too lazy to read our documentation. This would be an easy fix.

### CODE REVIEW

**Comment by DavidSCN** [comment]
@MakisH I guess this change could go to master as well?!

**Comment by MakisH** [comment]
> @MakisH I guess this change could go to master as well?!

Is it a bugfix or a feature? If it is a bugfix, in principle it goes to master. If it is a feature/"nice to have", it goes to develop. The question is essentially how urgent and breaking it is.

I guess it can go directly to master.

**Comment by DavidSCN** [comment]
You can decide yourself. It's just a usability improvement; not really a bug, not really a feature.

**Comment by DavidSCN** [comment]
There is another commit I don't want to mix here. Merging to develop.

**Pull request merged**
