### PR TITLE
Port elastic-tube-1d solvers to version 3

### PR DESCRIPTION
**Pull request by fsimonis**
This PR ports the elastic-tube-1d cpp solvers to version 3

This also rearranges the solvers to follow the pattern read data -> solve -> write data -> advance.

Also fixes the incorrect coordinates in solid-cpp #340

### CODE REVIEW

**Comment by fsimonis** [comment]
Related to https://github.com/precice/tutorials/issues/395

**Comment by valentin-seitz** [comment]
I just started a small system test job: https://github.com/precice/tutorials/actions/runs/7492877499/job/20397361340
And apparently, field-compare reports some major differences between the v2.5 reference data (we use the exchanged data between the participants) and the current status. (see stdout.log in the respective folders)
I just wanted to share this. It could also be a bug in the tests or some v2 vs. v3 hiccup.

**Review by IshaanDesai — APPROVED** [review]
I ran several combinations of the C++ and Python participants and everything seems to be working.

**Comment by fsimonis** [comment]
@valentin-seitz The solid-cpp solver was bugged and produced very bad results before 7de3813d2931c9fa9ad75db38f25faa9466ec5b4.
Could that be it.

Solid Cpp | Solid Python
--- | ---
1d-sc-fc | 1d-sp-fc

**Comment by fsimonis** [comment]
@valentin-seitz I checked the uploaded run of the workflow you linked to.

For the solid-python fluid-python case, fieldcompare fails, but the exports are close to identical apart from some minor differences. I checked provided meshes only. Is there a way to get more detailed information on what differs?

**Comment by fsimonis** [comment]
I ran the version 2 of the elastic-tube-1d with the watchpoint at x=5 on the Fluid Solver and then plotted them using the state of #438 (this PR + #435 + watchpoints and plotting).

The result is this:

tutorials-elastic-tube-1d-all

The results of the v2 python solid match the results of this PR.
The buggy (too coarse) solid solver of v2 leads to different results (larger max diameter in oscilations)

**Pull request merged**
