### PR TITLE
Two scale heat conduction: Enable running DuMux participants in parallel

### PR DESCRIPTION
**Pull request by mathiskelm**
Enables running both DuMux participants in parallel.

Checklist:

- [ ] I added a summary of any user-facing changes (compared to the last release) in the `changelog-entries/<PRnumber>.md`.
- [ ] I will remember to squash-and-merge, providing a useful summary of the changes of this PR.

### CODE REVIEW

**Comment by Fujikawas** [comment]
Thanks for the push. Should we also mention that if the micro manager config is not changed, `micro-dumux` only works with `-p 2`?

**Comment by mathiskelm** [comment]
> Thanks for the push. Should we also mention that if the micro manager config is not changed, `micro-dumux` only works with `-p 2`?

Both micro participants should be behaving the same way with respect to parallelisation, i.e. you can pass the number of processes to the run script and the decomposition in `micro-X/micro-manager-config.json` has to produce at least that many subdomains as [README.md#L69](https://github.com/precice/tutorials/blob/4f2323ca0e9359283ee6850eb82cb35b1e063d84/two-scale-heat-conduction/README.md?plain=1#L69) already mentions.

**Review by IshaanDesai — APPROVED** [review]
Glossed over and looks good :+1: Testing I leave to @Fujikawas

**Comment by Fujikawas** [comment]
Test with both parallel `macro-dumux` and `micro-dumux` could work :)

**Review by Fujikawas — APPROVED** [review]

**Pull request merged**
